import { z } from "zod"

import { HnThreadSchema, type HnThread } from "@/lib/schemas/critique"

// HN's public Algolia search. No auth, generous rate limits.
// Docs: https://hn.algolia.com/api
const HN_ENDPOINT = "https://hn.algolia.com/api/v1/search"
const HN_TIMEOUT_MS = 4000

// We validate only the fields we use. Items without a URL (Ask HN / Show
// HN self-posts) get a synthesized news.ycombinator.com permalink.
const AlgoliaHitSchema = z.object({
  title: z.string().nullable().optional(),
  url: z.string().url().nullable().optional(),
  points: z.number().int().nullable().optional(),
  num_comments: z.number().int().nullable().optional(),
  objectID: z.string(),
  story_id: z.number().int().nullable().optional(),
})

const AlgoliaResponseSchema = z.object({
  hits: z.array(AlgoliaHitSchema),
})

/**
 * Searches HN for threads matching `keywords`. The caller passes 2-3
 * domain terms (e.g. "deepfake detection") — typically generated by the
 * model itself, which knows the canonical jargon of the niche better
 * than any heuristic.
 *
 * Best-effort: any error (or no matches above the quality threshold)
 * resolves to an empty array so a flaky HN can't take down the whole
 * critique.
 */
export async function searchHnThreads(keywords: string): Promise<HnThread[]> {
  // Models sometimes return multiple comma-separated phrases when they
  // can think of more than one. Take the first phrase — that's the
  // canonical term, and HN's AND-semantics chokes on long mixed queries.
  const firstPhrase = keywords.split(/[,;|]/)[0] ?? keywords
  const query = firstPhrase.trim().slice(0, 80)
  if (!query) return []

  const url = new URL(HN_ENDPOINT)
  url.searchParams.set("query", query)
  url.searchParams.set("tags", "story")
  // Quality threshold: skip threads with <10 points. Submissions that
  // never caught traction aren't useful evidence of niche interest.
  url.searchParams.set("numericFilters", "points>=10")
  url.searchParams.set("hitsPerPage", "10")

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), HN_TIMEOUT_MS)

  try {
    const res = await fetch(url.toString(), { signal: controller.signal })
    if (!res.ok) return []
    const json = await res.json()
    const parsed = AlgoliaResponseSchema.safeParse(json)
    if (!parsed.success) return []

    const threads: HnThread[] = []
    for (const hit of parsed.data.hits) {
      const points = hit.points ?? 0
      const num_comments = hit.num_comments ?? 0
      const title = hit.title?.trim()
      if (!title) continue

      // Prefer the external URL the OP linked; fall back to the HN
      // permalink for Ask/Show HN posts where `url` is null.
      const link =
        hit.url ??
        `https://news.ycombinator.com/item?id=${hit.story_id ?? hit.objectID}`

      const candidate = { title, url: link, points, num_comments }
      const v = HnThreadSchema.safeParse(candidate)
      if (v.success) threads.push(v.data)
    }

    // Rank by engagement (points + comments). Top 3 is enough to signal
    // the niche without drowning the UI.
    threads.sort(
      (a, b) => b.points + b.num_comments - (a.points + a.num_comments)
    )
    return threads.slice(0, 3)
  } catch {
    return []
  } finally {
    clearTimeout(timer)
  }
}
